// Code generated by protoc-gen-gin. DO NOT EDIT.

package proto

import (
	http "net/http"

	gin "github.com/gin-gonic/gin"
)

type HelloHttpServer struct {
	server HelloServer
	router gin.IRouter
}

func RegisterHelloServerHTTPServer(srv HelloServer, r gin.IRouter) {
	s := HelloHttpServer{
		server: srv,
		router: r,
	}
	s.RegisterService()
}

func (s *HelloHttpServer) SayHello_0(c *gin.Context) {
	var in SayHelloReq

	if err := c.ShouldBindJSON(&in); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
		return
	}

	out, err := s.server.SayHello(c, &in)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	c.JSON(http.StatusOK, out)
}

func (s *HelloHttpServer) RegisterService() {

	s.router.Handle("POST", "", s.SayHello_0)

}
