// Code generated by "stringer -type=ErrCode -linecomment"; DO NOT EDIT.

package ginx

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ErrSuccess-0]
	_ = x[ErrInternalServer - -1]
	_ = x[ErrBadRequest - -400]
	_ = x[ErrUnauthorized - -401]
	_ = x[ErrNotFound - -404]
}

const (
	_ErrCode_name_0 = "not found"
	_ErrCode_name_1 = "unauthorizedinvalid argument"
	_ErrCode_name_2 = "internal server errorsuccess"
)

var (
	_ErrCode_index_1 = [...]uint8{0, 12, 28}
	_ErrCode_index_2 = [...]uint8{0, 21, 28}
)

func (i ErrCode) String() string {
	switch {
	case i == -404:
		return _ErrCode_name_0
	case -401 <= i && i <= -400:
		i -= -401
		return _ErrCode_name_1[_ErrCode_index_1[i]:_ErrCode_index_1[i+1]]
	case -1 <= i && i <= 0:
		i -= -1
		return _ErrCode_name_2[_ErrCode_index_2[i]:_ErrCode_index_2[i+1]]
	default:
		return "ErrCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
